config/routes.rb
Bkchannel3::Application.routes.draw do |map|
  root :to => "sessions#new"
  resources :users
  resources :messages
  resource :session
  resources :seats
  
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"  
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :body, :presence => true
  belongs_to :user
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.xml
  def index
    @users = User.where(:nickname => session[:user_nickname]).first
    @message = Message.new
    @messages = Message.where(:receiver => [session[:user_nickname], 'public']).all(:order => 'created_at ASC')
    @seats = Seat.all(:order => 'seatno ASC')
    
    respond_to do |format|
      format.html # index.html.erb
    end
  end
  
  # GET /messages/1
  # GET /messages/1.xml
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.xml
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.xml
  def create
    txt = params[:message][:body]
    recver = params[:message][:receiver]
    @users = User.where(:nickname => session[:user_nickname]).first
    @message = Message.new(:nickname => session[:user_nickname], :body => txt, 
                           :receiver => recver, :created_at => Time.now)
    
    if ((Message.where(:receiver => [session[:user_nickname], 'public']).all.count) > 4) 
        @message2 = Message.where(:receiver => [session[:user_nickname], 'public']).find(:first)
        @message2.destroy
     end

    respond_to do |format|
      if @message.save
         format.html { redirect_to(messages_url, :notice => 'Message was successfully created.') }
         format.js
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end


  # DELETE /messages/1
  # DELETE /messages/1.xml
  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    
    respond_to do |format|
    format.html { redirect_to(messages_url) }
    format.js
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message, :remote => true) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :receiver %> (Note: Type here Receiver's Nickname. Otherwise type 'public' to send to all!)<br />
    <%= f.text_field :receiver %>
  </div>
  <div class="field">
    Message <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<%= content_tag_for(:li, message) do %>

  <font color="rrggbb"><br>(From:<%= message.nickname %>=>To:<%= message.receiver %>)</font>
  @<%= message.body %>::<%= message.created_at %>
  <%= link_to 'Delete', message, :confirm => 'Are you sure?', :method => :delete, :remote => true %>

<% end %>

app/views/messages/create.js.erb
$('#messages').prepend('<%= escape_javascript(render(@message)) %>');
$('#messages > li:first').effect('highlight', {}, 3000);
$('#message_form > form')[0].reset();
$(function() { alert('A message is created!!');});


//$('#test10').replaceWith('Hello world!');

app/views/messages/destroy.js.erb
$('#<%= dom_id(@message) %>').css('background', 'red');
//$('#<%= dom_id(@message) %>').hide("fade", {}, 1500);
$(function(){ location.reload();});

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<center>
<h1>Welcome to Backchannel System!!</h1>
<br>
<% if @users %>
<font color="#FF00FF">(login user::<%= @users.nickname %>)</font>
<% end %>

<h3>Classroom Seating Chart</h3>

<div id="seats">
<table border= "3" width= "50" height= "150" cellpadding="5" cellspacing="5">
<tr>

<% @seats.each do |seat| %>
    <td bgcolor= "ADD8E6">Seat#:<%= seat.seatno %></td>  
    <% if @users %>
          <% if (seat.nickname != 'empty') %>
             <td bgcolor = #FF00FF><%= seat.nickname %></td>
             <td>Selected</td>     
          <% else %><td><%= seat.nickname %></td>
                    <td><%= link_to 'Select', edit_seat_path(seat, :format => :js), :remote => true %></td>    
          <% end %>
  <% else %>
          <td><%= seat.nickname %></td>
           <td>Select</td>        
  <% end %>  
    <% if((seat.seatno % 4) == 0 )%> </tr><% end %>
<% end %>
</table>
</div>

<br>
<h3>Live Chat Room</h3>
<div style= "background-color:orange; width:800px; height:200px">
<div align="left">
  
  <ul id="messages">
  <%= render :partial => @messages.reverse %>
  </ul>
</div>  
</div>

<div id="message_form">  
  <%= render 'form' %>
</div>

<br />
<%= link_to 'logout', '/logout' %>
</center>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Receiver:</b>
  <%= @message.receiver %>
</p>

<p>
  <b>Body:</b>
  <%= @message.body %>
</p>

<p>
  <b>Created at:</b>
  <%= @message.created_at %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>