config/routes.rb
Bkchannel3::Application.routes.draw do |map|
  root :to => "sessions#new"
  resources :users
  resources :messages
  resource :session
  resources :seats
  
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"  
end

app/models/seat.rb
class Seat < ActiveRecord::Base
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController  
  # GET /seats
  # GET /seats.xml
  def index
    @seats = Seat.all(:order => 'seatno ASC')
    @users = User.where(:nickname => session[:user_nickname]).first

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @seats }
    end
  end


  # GET /seats/1
  # GET /seats/1.xml
  def show
   @seat = Seat.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @seat }
    end
  end

  # GET /seats/new
  # GET /seats/new.xml
  def new
    @seat = Seat.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @seat }
    end
  end

  # GET /seats/1/edit
  def edit
    @seat = Seat.find(params[:id])
  end

  # POST /seats
  # POST /seats.xml
  def create
  
    @seat = Seat.new(params[:seat])

    respond_to do |format|
      if @seat.save
        format.html { redirect_to(@seat, :notice => 'Seat was successfully created.') }
        format.xml  { render :xml => @seat, :status => :created, :location => @seat }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @seat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /seats/1
  # PUT /seats/1.xml
  def update
    @users = User.where(:nickname => session[:user_nickname]).first
    @seat = Seat.find(params[:id])
    
    if @users
      txt = params[:seat][:seatno]
    else
      txt = params[:seat]
    end
    
    @seat2 = Seat.where(:nickname => session[:user_nickname]).first
    if @seat2
      @seat2.update_attributes(:nickname => 'empty')
    end

    respond_to do |format|
    if @users   
      if @seat.update_attributes(:seatno => txt, :nickname => session[:user_nickname])
        format.html { redirect_to(messages_url, :notice => 'Seat was successfully updated.') }
        format.js
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @seat.errors, :status => :unprocessable_entity }
      end
   else   
      if @seat.update_attributes(params[:seat])
        format.html { redirect_to(messages_url, :notice => 'Seat was successfully updated.') }
        format.js
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @seat.errors, :status => :unprocessable_entity }
      end   
    end 
      
   end
  end

  # DELETE /seats/1
  # DELETE /seats/1.xml
  def destroy
    @seat = Seat.find(params[:id])
    @seat.destroy

    respond_to do |format|
      format.html { redirect_to(seats_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/seats/_form.html.erb
<%= form_for(@seat, :remote => true) do |f| %>
  <% if @seat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
      <% @seat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :seatno %><br />
    <%= f.text_field :seatno %>
  </div>

  <div class="field">
    <%= f.label :nickname%>(Note: Don't need to type your nickname here if you've aleady logged in!)<br />
    <%= f.text_field :nickname %>
  </div>  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seats/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

app/views/seats/edit.js.erb
$(function() { alert('You are trying to change your seat!!');});
$("<%= escape_javascript render(:file => 'seats/edit.html.erb') %>").insertAfter('#seats');

app/views/seats/index.html.erb
<center><br><br>
<h1>Class Seating Chart</h1>
<br><br>
<table border= "3" width= "100" height= "300" cellpadding="5" cellspacing="5">

<tr>
<% @seats.each do |seat| %>
    <td bgcolor= "ADD8E6">Seat#:<%= seat.seatno %></td>  
    <% if @users %>
          <% if (seat.nickname != 'empty') %>
             <td bgcolor = #FF00FF><%= seat.nickname %></td>    
          <% else %><td><%= seat.nickname %></td>    
          <% end %>
  <% else %>
          <td><%= seat.nickname %></td>    
  <% end %>  
  <% if((seat.seatno % 4) == 0 )%> </tr><% end %>
<% end %>
</table>
<br>
<%= link_to 'Login', '/login' %>

app/views/seats/new.html.erb
<h1>New seat</h1>

<%= render 'form' %>

<%= link_to 'Back', seats_path %>

app/views/seats/seat.js.erb
$(function() { alert('A seat is updated!!');});

app/views/seats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Seatno:</b>
  <%= @seat.seatno %>
</p>

<p id= seats>
  <b>Nickname:</b>
  <%= @seat.nickname %>
</p>

<%= link_to 'Back', messages_path %>

<!-- <%=link_to_function "Greeting", "$(function() {alert('Test44444444444444');})" %> -->

<!-- <%=link_to_function "Greeting", "$(function() {location.reload();)" %> -->



<%= link_to "new seat", new_seat_path(@seat, :format => :js),
:remote => true, :id => 'new_seat_link' %>

app/views/seats/update.js.erb
$(function() { alert('Your seat is changed!!');});
$(function(){ window.location.href = '/messages';});